name: appetite_demo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  bubbled_navigation_bar: ^0.0.3

  animated_bottom_navigation_bar: ^0.3.2
  auto_size_text: ^2.1.0

  loading_overlay: ^0.2.1




  #FIREBASE PLUGINS
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  google_sign_in: ^4.5.3
  google_sign_in_web: ^0.9.1+1
  firebase_storage: ^4.0.0
  firebase_core: ^0.5.0

  cloud_firestore_web: ^0.2.0+1
  carousel_slider: ^2.3.1



  bloc_pattern:
  rxdart:
  flutter_phoenix: ^0.1.0
  provider: ^4.3.2+1
  toggle_switch: ^0.1.9
  fluttertoast: ^8.0.6
  flutter_easyloading: ^3.0.0
  intl:
  anim_search_bar: ^2.0.1



  progress_dialog: ^1.2.4
  loading_animations: ^2.1.0

  #google_maps_flutter: ^2.0.3
  map: ^0.3.0
  latlng: ^0.1.0


  #STORAGE AND SHARED PREFERENCES
  shared_preferences: ^2.0.5

















dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:



  uses-material-design: true

  assets:
    - assets/
    - assets/images/
